language: ruby
addons:
  apt:
    packages:
      - postgresql-11
      - postgresql-11-postgis-2.5
      - postgresql-11-postgis-2.5-scripts
  postgresql: '11'
before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo service postgresql stop
  - sudo service postgresql start 11
services:
  - postgresql
rvm:
  - 2.6.0
script:
  - bundle exec rake db:create db:gis:setup
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec
env:
  - PG_USERNAME='postgres'
