language: ruby
addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3
before_script:
  - psql -U postgres -c "create extension postgis"
rvm:
  - 2.6.0
script:
  - bundle exec rake db:create db:gis:setup
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec spec
env:
  - PG_USERNAME='postgres'
